name: first
description: A Dart app that uses Angular 2
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: ^2.0.0
  dnd: ^0.3.5
  http: ^0.11.0
  stream_transformers: ^0.3.0
  firebase: ^3.0.0
  markdown: ^0.11.2
  uuid: ^0.5.3
  intl: ^0.14.0
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
transformers:
- angular2:
    entry_points:
      - web/main.dart
      - web/admin/main.dart
    platform_pipes:
      - 'package:angular2/common.dart#COMMON_PIPES'
    resolved_identifiers:
      BrowserClient: 'package:http/browser_client.dart'
      Client: 'package:http/http.dart'
    platform_directives: 'package:angular2/common.dart#CORE_DIRECTIVES'
    entry_points:
      - 'web/main.dart'
      - 'web/admin/main.dart'
- dart_to_js_script_rewriter

